### ISSUE TITLE
Changing desired temperature

### ISSUE THREAD

**Issue by Pilaarbijter** [Danielhiversen/pyAdax#9]
I was able to query the the heating without a problem thanks to your example code. 

However I am wondering how I actually change the desired temperature?

Thanks!

**Comment by Danielhiversen** [comment]
https://github.com/Danielhiversen/pyAdax/blob/de8f8a5f6e07a6261c3f77ee2431ee53a402be35/adax/__init__.py#L53

**Comment by Pilaarbijter** [comment]
I have found that command aswel digging around in the code but I can't seem to get it to work.

I'm completely new to Python, could you perhaps provide me with an complete example?
Thank you!

**Comment by Danielhiversen** [comment]
https://github.com/home-assistant/core/blob/ce3d774222f62470b9c7f8e25f2194a92cc07b49/homeassistant/components/adax/climate.py#L98

**Comment by Pilaarbijter** [comment]
This is code to a HomeAssistant integration?

I was thinking about an example like the one on the page of this repo. 

---
from adax import Adax
import aiohttp
import asyncio

ACCOUNTID = "<ACCOUNT ID>"  # get your account ID (6 digits) from the Account page in the Adax WiFi app
PASSWORD = "<PASSWORD>" # create a service password under "Remote Api" in the app

async def main():
    async with aiohttp.ClientSession() as session:
        heater= Adax(ACCOUNTID, PASSWORD, session)
        for room in await heater.get_rooms():
            print(room)

asyncio.run(main())

-----------

This actually works for me but I would just like to adjust the temp with a similar script.
